const productos = [
    {
        id: 1,
        productName: "Valle Grande",
        duration: "5 días",
        DepartureDate: "8 dic. 2023",
        departureTime: "08:00",
        arrivalTime: "08:45",   
        price: 2800,
        quanty: 1,
        img: "../media/valle_grande.jpg",
    },
    {
        id: 2,
        productName: "El Nihuil",
        duration: "4 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "08:45",
        price: 3500,
        quanty: 1,
        img: "../media/el_nihuil.jpg",
    },
    {
        id: 3,
        productName: "Los Reyunos",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "07:45",
        price: 3200,
        quanty: 1 ,
        img: "../media/los_reyunos.jpg",
    },
    {
        id: 4,
        productName: "El Sosneado",
        duration: "2 días",
        DepartureDate: "16 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "09:15",
        price: 4300,
        quanty: 1,
        img: "../media/el_sosneado.jpg",
    },    
];
const productosAmigos = [
    {
        id: 1,
        productName: "Valle Grande",
        duration: "5 días",
        DepartureDate: "8 dic. 2023",
        departureTime: "08:00",
        arrivalTime: "08:45",   
        price: 2800,
        quanty: 1,
        img: "../media/valle_grande.jpg",
    },
    {
        id: 2,
        productName: "El Nihuil",
        duration: "4 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "08:45",
        price: 3500,
        quanty: 1,
        img: "../media/el_nihuil.jpg",
    },
    {
        id: 3,
        productName: "Los Reyunos",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "07:45",
        price: 3200,
        quanty: 1 ,
        img: "../media/los_reyunos.jpg",
    },
        
];
const productosFamilia = [
    {
        id: 1,
        productName: "Valle Grande",
        duration: "7 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "08:00",
        arrivalTime: "08:45",   
        price: 7000,
        cantidad: "4 personas",
        quanty: 1,
        img: "../media/valle_grande.jpg",
    },
    {
        id: 2,
        productName: "El Nihuil",
        duration: "4 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "08:45",
        price: 5000,
        cantidad: "4 personas",
        quanty: 1,
        img: "../media/el_nihuil.jpg",
    },
    {
        id: 3,
        productName: "Los Reyunos",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "07:45",
        price: 4000,
        cantidad: "4 personas",
        quanty: 1 ,
        img: "../media/los_reyunos.jpg",
    },
       
];
const productosSolos = [
    {
        id: 1,
        productName: "Valle Grande",
        duration: "5 días",
        DepartureDate: "8 dic. 2023",
        departureTime: "08:00",
        arrivalTime: "08:45",   
        price: 2800,
        quanty: 1,
        img: "../media/valle_grande.jpg",
    },
    {
        id: 2,
        productName: "El Nihuil",
        duration: "4 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "08:45",
        price: 3500,
        quanty: 1,
        img: "../media/el_nihuil.jpg",
    },
    {
        id: 3,
        productName: "Los Reyunos",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "07:45",
        price: 3200,
        quanty: 1 ,
        img: "../media/los_reyunos.jpg",
    },
       
];