const productos = [
    {
        id: 1,
        productName: "Valle Grande",
        duration: "5 días",
        DepartureDate: "8 dic. 2023",
        departureTime: "08:00",
        arrivalTime: "08:45",   
        price: 2800,
        quanty: 1,
        img: "../media/valle_grande.jpg",
    },
    {
        id: 2,
        productName: "El Nihuil",
        duration: "4 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "08:45",
        price: 3500,
        quanty: 1,
        img: "../media/el_nihuil.jpg",
    },
    {
        id: 3,
        productName: "Los Reyunos",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "07:45",
        price: 3200,
        quanty: 1 ,
        img: "../media/los_reyunos.jpg",
    },
    {
        id: 4,
        productName: "El Sosneado",
        duration: "2 días",
        DepartureDate: "16 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "09:15",
        price: 4300,
        quanty: 1,
        img: "../media/el_sosneado.jpg",
    },    
];
const productosAmigos = [
    {
        id: 1,
        productName: "Bariloche",
        duration: "5 días",
        DepartureDate: "10 Jul. 2024",
        departureTime: "08:00",
        arrivalTime: "15:00",   
        price: 28000,
        quanty: 1,
        img: "",
    },
    {
        id: 2,
        productName: "Carlos Paz",
        duration: "4 días",
        DepartureDate: "11 Febrero. 2024",
        departureTime: "07:00",
        arrivalTime: "14:00",
        price: 36000,
        quanty: 1,
        img: "",
    },
    {
        id: 3,
        productName: "Mar del Plata",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "14:45",
        price: 60000,
        quanty: 1 ,
        img: "",
    },
        
];
const productosFamilia = [
    {
        id: 1,
        productName: "Cataratas del Iguazú",
        duration: "7 días",
        DepartureDate: "9 Dic. 2023",
        departureTime: "08:00",
        arrivalTime: "17:00",   
        price: 120000,
        cantidad: "5 personas",
        quanty: 1,
        img: "",
    },
    {
        id: 2,
        productName: "Las Leñas",
        duration: "4 días",
        DepartureDate: "20 Jul. 2024",
        departureTime: "07:00",
        arrivalTime: "11:45",
        price: 200000,
        cantidad: "4 personas",
        quanty: 1,
        img: "",
    },
    {
        id: 3,
        productName: "Glaciar Perito Moreno",
        duration: "4 días",
        DepartureDate: "10 Mar. 2024",
        departureTime: "07:00",
        arrivalTime: "15:45",
        price: 120000,
        cantidad: "4 personas",
        quanty: 1 ,
        img: "",
    },
    
];
const productosSolos = [
    {
        id: 1,
        productName: "Salta",
        duration: "5 días",
        DepartureDate: "8 Ago. 2024",
        departureTime: "08:00",
        arrivalTime: "15:30",   
        price: 90000,
        quanty: 1,
        img: "",
    },
    {
        id: 2,
        productName: "El Chalten",
        duration: "6 días",
        DepartureDate: "11 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "14:45",
        price: 100000,
        quanty: 1,
        img: "",
    },
    {
        id: 3,
        productName: "Buenos Aires",
        duration: "2 días",
        DepartureDate: "9 dic. 2023",
        departureTime: "07:00",
        arrivalTime: "12:45",
        price: 60000,
        quanty: 1 ,
        img: "",
    },
       
];